import hashlib
import json
from pathlib import Path
from typing import Any, Iterator, overload

from pydantic import BaseModel, Field

MAX_HASH_LENGTH = 12


def stable_hash(s: str, max_length: int = MAX_HASH_LENGTH) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:max_length]


class Solution(BaseModel):
    model: str = Field(description="The model that generated the solution")
    solution: str = Field(description="The solution generated by the model")
    id: str = Field(default_factory=lambda: "")

    metadata: dict = Field(
        default_factory=dict,
        description="Metadata, like 'paraphrased', 'formatted', etc",
    )

    def model_post_init(self, __context: Any):
        self.id = stable_hash(self.solution + self.model)

    def check_filter(self, **kwargs: Any) -> bool:
        for key, value in kwargs.items():
            if key in self.metadata:
                if self.metadata[key] != value:
                    return False
            elif key == "model":
                if self.model != value:
                    return False
            elif key == "solution":
                if self.solution != value:
                    return False
            elif key == "id":
                if self.id != value:
                    return False
            else:
                return False
        return True


class ProblemSolutions(BaseModel):
    """
    A collection of solutions for a single problem from the APPS dataset.

    This class represents a problem and all its associated solutions generated
    by different models. It provides filtering capabilities and supports
    iteration over solutions.

    Attributes:
        apps_problem_id: The unique identifier from the APPS dataset
        problem_statement: The text description of the problem
        solutions: list of Solution objects containing model outputs

    Examples:
        Create a new problem with solutions:
        >>> problem = ProblemSolutions(
        ...     apps_problem_id=123,
        ...     problem_statement="Write a function to add two numbers",
        ...     solutions=[
        ...         Solution(model="gpt-4", solution="def add(a, b): return a + b"),
        ...         Solution(model="claude-3", solution="def add(x, y): return x + y")
        ...     ]
        ... )

        Filter solutions by model:
        >>> filtered = problem.filter(model="gpt-4")
        >>> len(filtered.solutions)
        1

        Iterate over solutions:
        >>> for solution in problem:
        ...     print(solution.model)
        gpt-4
        claude-3

        Access solutions by index:
        >>> first_solution = problem[0]
        >>> print(first_solution.model)
        gpt-4
    """

    apps_problem_id: int = Field(description="The problem id from the APPS dataset")
    problem_statement: str = Field(description="The problem statement")
    solutions: list[Solution]

    def __len__(self):
        return len(self.solutions)

    def __getitem__(self, index: int) -> Solution:
        return self.solutions[index]

    def __iter__(self) -> Iterator[Solution]:
        return iter(self.solutions)

    def filter(self, **kwargs: Any) -> "ProblemSolutions":
        return ProblemSolutions(
            apps_problem_id=self.apps_problem_id,
            problem_statement=self.problem_statement,
            solutions=[
                solution
                for solution in self.solutions
                if solution.check_filter(**kwargs)
            ],
        )

    def check_filter(self, **kwargs: Any) -> bool:
        for k, v in kwargs.items():
            if k == "apps_problem_id":
                return v == self.apps_problem_id
        return True

    def merge(self, other: "ProblemSolutions") -> "ProblemSolutions":
        """
        Merge two problem solutions with same id together. Smartly merges the solutions, removing duplicates.
        """
        assert self.apps_problem_id == other.apps_problem_id
        assert self.problem_statement == other.problem_statement, (
            f"Seems like two different problems with the same id: {self.apps_problem_id}. Check if the data folder contains data from both train and test splits.\nFirst problem: {self.problem_statement[:100]}...\ncontains {len(self.solutions)} solutions from the following models: {', '.join(set([s.model for s in self.solutions]))}\nSecond problem: {other.problem_statement[:100]}...\ncontains {len(other.solutions)} solutions from the following models: {', '.join(set([s.model for s in other.solutions]))}"
        )
        # deduplicating solutions
        total_solutions = self.solutions + other.solutions
        ids = set()
        solutions = []
        for solution in total_solutions:
            if solution.id not in ids:
                ids.add(solution.id)
                solutions.append(solution)
        return ProblemSolutions(
            apps_problem_id=self.apps_problem_id,
            problem_statement=self.problem_statement,
            solutions=solutions,
        )


class Dataset(BaseModel):
    problems: list[ProblemSolutions]
    id_to_problem_map: dict[int, ProblemSolutions] = Field(default_factory=dict)

    def model_post_init(self, __context: Any):
        self.id_to_problem_map = {
            problem.apps_problem_id: problem for problem in self.problems
        }

    @classmethod
    def read(cls, path: str | Path) -> "Dataset":
        """
        Read a dataset from a file or directory.
        If path is a file, read a single dataset from the file.
        If path is a directory, read all datasets from the directory and merge them together.
        """
        path = Path(path)
        if path.is_file():
            dataset = Dataset.model_validate_json(path.read_text())
        else:
            dataset = Dataset(problems=[])
            for file in path.iterdir():
                dataset = dataset.merge(cls.read(file))
        return dataset

    def to_json(self, path: str | Path):
        with open(path, "w+") as f:
            json.dump(self.model_dump(), f, indent=2)

    def __len__(self):
        return len(self.problems)

    @overload
    def __getitem__(self, index: slice) -> "Dataset": ...
    @overload
    def __getitem__(self, index: int) -> ProblemSolutions: ...

    def __getitem__(self, index: slice | int) -> "Dataset | ProblemSolutions":
        if isinstance(index, slice):
            return Dataset(problems=self.problems[index])
        elif isinstance(index, int):
            return self.problems[index]
        else:
            raise ValueError(f"Invalid index: {index}")

    def get_problem_by_id(self, problem_id: int) -> ProblemSolutions | None:
        if problem_id not in self.id_to_problem_map:
            return None
        return self.id_to_problem_map[problem_id]

    def __iter__(self) -> Iterator[ProblemSolutions]:
        return iter(self.problems)

    def merge(self, other: "Dataset") -> "Dataset":
        """
        Merge two datasets together. Smartly merges the problems and their solutions, removing duplicates.
        """
        problems_by_id = {
            problem.apps_problem_id: [problem] for problem in self.problems
        }
        for problem in other.problems:
            if problem.apps_problem_id in problems_by_id:
                problems_by_id[problem.apps_problem_id].append(problem)
            else:
                problems_by_id[problem.apps_problem_id] = [problem]
        merged_problems = []
        for problem_id in problems_by_id:
            base_problem = problems_by_id[problem_id][0]
            if len(problems_by_id[problem_id]) > 1:
                for problem in problems_by_id[problem_id][1:]:
                    base_problem = base_problem.merge(problem)
            merged_problems.append(base_problem)
        return Dataset(
            problems=merged_problems,
        )

    def filter(self, **kwargs: Any) -> "Dataset":
        """
        Filter the dataset based on solution criteria.

        This method filters problems by their solutions. A problem is included
        in the result if it has at least one solution that matches the filter
        criteria. The filter criteria can include model names or metadata fields.

        Args:
            **kwargs: Filter criteria. Can include:
                - model: Filter by model name (e.g., "claude-3-5-sonnet-20240620")
                - Any metadata field from Solution.metadata

        Returns:
            A new Dataset containing only problems with solutions matching the criteria.

        Examples:
            >>> # Filter by model name
            >>> dataset.filter(model="claude-3-5-sonnet-20240620")

            >>> # Filter by metadata field
            >>> dataset.filter(formatted=True)

            >>> # Combine multiple criteria
            >>> dataset.filter(model="gpt-4", paraphrased=True)
        """
        problems = [
            problem.filter(**kwargs)
            for problem in self.problems
            if problem.check_filter(**kwargs)
        ]
        return Dataset(problems=[p for p in problems if len(p.solutions) > 0])

    def describe(
        self, per_problem_info: bool = False, per_model_info: bool = False
    ) -> str:
        """
        Describe the dataset.
        """
        descr = f"Dataset with {len(self.problems)} problems and {len([s for p in self.problems for s in p.solutions])} solutions\n"

        if per_model_info:
            descr += "\n\n"
            for model in set([s.model for p in self.problems for s in p.solutions]):
                descr += f"{model:>25}:{len([s for p in self.problems for s in p.solutions if s.model == model]):>6} solutions\n"

        if per_problem_info:
            descr += "\n\n"
            for problem in self.problems:
                descr += f"Problem {problem.apps_problem_id}:\n"
                descr += f"  - {len(problem.solutions)} solutions\n"
                if per_model_info:
                    # Count solutions by model
                    model_counts = {}
                    for solution in problem.solutions:
                        model = solution.model
                        model_counts[model] = model_counts.get(model, 0) + 1

                    # Display counts for each model
                    for model, count in sorted(model_counts.items()):
                        descr += f"    - {count} solutions from {model}\n"
        return descr
