experiment_folder: experiments/apps/self_rec

experiment_name: self_rec_generatorx

results_folder: results/

defaults:
  data_split: test 

runs:
   attacks:
    eval_mode: attack
    system_prompt: self_rec_subtle_attack_policy_prompt
    save_path: generator/attacks.eval
    model: tinker/<untrusted_generator_model_name>  

   honeypots:
    eval_mode: attack
    system_prompt: self_rec_subtle_attack_policy_prompt
    save_path: generator/honeypots.eval
    model: tinker/<honeypot-generator-model-name>
  
   honest:
    eval_mode: honest 
    system_prompt: honest_policy_prompt
    save_path: generator/honest.eval 
    model: tinker/<untrusted_generator_model_name>  
 

   

